//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
<<<<<<< HEAD
//     the code is regenerated.
=======
//     the code is regenerated. 
>>>>>>> 6a26bd3 (Modificando)
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms_TP3_Equipo27
{


    public partial class Default
    {
<<<<<<< HEAD
=======

        /// <summary>
        /// repRepetidor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater repRepetidor;
>>>>>>> 6a26bd3 (Modificando)
    }
}
